# system configuration generated and used by the sysconfig module
build_time_vars = {'ABIFLAGS': '',
 'AR': 'ar',
 'ARFLAGS': 'rc',
 'CC': 'gcc -pthread',
 'CCSHARED': '-fPIC',
 'CFLAGS': '-DNDEBUG -O2',
 'CONFINCLUDEPY': '/build_dir/pypy-c-jit-linux-x86-64/build/include/pypy3.10',
 'CXX': 'g++ -pthread',
 'EXE': '',
 'EXT_SUFFIX': '.pypy310-pp73-x86_64-linux-gnu.so',
 'GNULD': 'yes',
 'HOST_GNU_TYPE': 'x86_64-pc-linux-gnu',
 'INCLUDEPY': '/build_dir/pypy-c-jit-linux-x86-64/build/include/pypy3.10',
 'LDFLAGS': '-Wl,-Bsymbolic-functions',
 'LDLIBRARY': 'libpypy3.9-c.so',
 'LDSHARED': 'gcc -pthread -shared -Wl,-Bsymbolic-functions',
 'LDVERSION': '3.10',
 'LIBDIR': '/build_dir/pypy-c-jit-linux-x86-64/build/bin',
 'MULTIARCH': 'x86_64-linux-gnu',
 'OPT': '-DNDEBUG -O2',
 'Py_DEBUG': 0,
 'Py_ENABLE_SHARED': 0,
 'SHLIB_SUFFIX': '.so',
 'SIZEOF_VOID_P': 8,
 'SO': '.pypy310-pp73-x86_64-linux-gnu.so',
 'SOABI': 'pypy310-pp73',
 'TZPATH': '/build_dir/pypy-c-jit-linux-x86-64/build/share/zoneinfo:/build_dir/pypy-c-jit-linux-x86-64/build/lib/zoneinfo:/build_dir/pypy-c-jit-linux-x86-64/build/share/lib/zoneinfo:/build_dir/pypy-c-jit-linux-x86-64/build/../etc/zoneinfo:/usr/share/zoneinfo:/usr/lib/zoneinfo:/usr/share/lib/zoneinfo:/etc/zoneinfo',
 'VERSION': '3.10'}
